# ===================================
#  Relation Behavior Config
# ===================================

phone:
    label: Phone
    form: ~/plugins/october/test/models/phone/fields1.yaml
    list: ~/plugins/october/test/models/phone/columns.yaml
